# Base de datos H2
db.url=jdbc:h2:file:./data/denuncias;AUTO_SERVER=TRUE;TRACE_LEVEL_FILE=0
db.username=sa
db.password=

db.ddl.auto=true
db.ddl.script=schema.sql

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.username=apazashan@gmail.com
mail.smtp.password=xefuopwzuxjffchg
mail.smtp.from=apazashan@gmail.com
mail.smtp.from.name=Sistema de Denuncias - Municipalidad